[package]
name = "console-log-saver"
version = "1.3.0-beta.2"
edition = "2021"

[dependencies]
libui = { git = "https://github.com/libui-rs/libui", version = "0.4.0", rev = '4bdb78d', optional = true }

[[bin]]
name = "ConsoleLogSaverGui"
path = "src/gui.rs"
required-features = ['gui']

[features]
gui = [ "dep:libui" ]
