[package]
name = "console-log-saver"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.19.0"
byteorder = "1.5.0"
lldb = { git = "https://github.com/endoli/lldb.rs.git", version = "0.0.11" }
tempfile = "3.14.0"

[workspace]
members = [
    'cls-attach-lib', 
    'monobdwgc-2.0-stub',
]

[patch.crates-io]
lldb-sys = { git = "https://github.com/anatawa12/lldb-sys.rs", branch = "static-link" }
