//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anatawa12.ConsoleLogSaver.Gui {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ConsoleLogSaver.Gui.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TwoInstanceDetected {
            get {
                return ResourceManager.GetString("TwoInstanceDetected", resourceCulture);
            }
        }
        
        internal static string UpdateRunningUnityList {
            get {
                return ResourceManager.GetString("UpdateRunningUnityList", resourceCulture);
            }
        }
        
        internal static string SecuritySettings {
            get {
                return ResourceManager.GetString("SecuritySettings", resourceCulture);
            }
        }
        
        internal static string UnityVersion {
            get {
                return ResourceManager.GetString("UnityVersion", resourceCulture);
            }
        }
        
        internal static string HideOSInfo {
            get {
                return ResourceManager.GetString("HideOSInfo", resourceCulture);
            }
        }
        
        internal static string HideUserName {
            get {
                return ResourceManager.GetString("HideUserName", resourceCulture);
            }
        }
        
        internal static string HideUserHome {
            get {
                return ResourceManager.GetString("HideUserHome", resourceCulture);
            }
        }
        
        internal static string HideAwsApiKey {
            get {
                return ResourceManager.GetString("HideAwsApiKey", resourceCulture);
            }
        }
        
        internal static string HideAwsUploadSignature {
            get {
                return ResourceManager.GetString("HideAwsUploadSignature", resourceCulture);
            }
        }
        
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        internal static string VersionAndCheckingForUpdates {
            get {
                return ResourceManager.GetString("VersionAndCheckingForUpdates", resourceCulture);
            }
        }
        
        internal static string VersionAndLatest {
            get {
                return ResourceManager.GetString("VersionAndLatest", resourceCulture);
            }
        }
        
        internal static string VersionAndFailed {
            get {
                return ResourceManager.GetString("VersionAndFailed", resourceCulture);
            }
        }
        
        internal static string VersionAndNewFound {
            get {
                return ResourceManager.GetString("VersionAndNewFound", resourceCulture);
            }
        }
    }
}
