on:
  push:
    branches: [ master, reimplement-with-debugger-protocol ]
  pull_request:
    branches: [ master, reimplement-with-debugger-protocol ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: zip
          path-type: inherit
          release: false
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: dotnet --version
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-restore

      # finally run build script for release
      - run: ./build.sh
        shell: msys2 {0}
      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: bin
