on:
  push:
    branches: [ master, lldb-implementation ]
  pull_request:
    branches: [ master, lldb-implementation ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
            additional-target: x86_64-apple-darwin
          - runs-on: windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.additional-target }}
      - run: ./build.sh
      - run: ./build.sh --target ${{ matrix.additional-target }}
        if: ${{ matrix.additional-target }}

      - uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.runs-on }}
          path: target/*/ConsoleLogSaver*
