on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      publish:
        description: "True to publish release to git, vpm. if false, this creates release asset only"
        type: boolean
        required: false

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: anatawa12/something-releaser@v2
      - uses: snow-actions/git-config-user@v1.0.0

      - name: Update Version Name
        id: update-version
        run: |
          VERSION="$(get-version)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          {
            echo "$VERSION"
            echo "# second line or later may be used for other reason later"
          } > latest.txt

      - name: Commit & tag version
        if: ${{ inputs.publish }}
        run: |
          git commit -am "$VERSION"
          git tag "v$VERSION"

      - run: ./build.sh
      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          path: bin

      - name: Publish Release
        if: ${{ inputs.publish }}
        run: |
          git push && git push origin "v$VERSION"

      - name: Publish release to github
        if: ${{ inputs.publish }}
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          sleep 1
          # upload release assets
          gh release create "v$VERSION" \
            bin/* \

      - name: prepare next release & push
        if: ${{ inputs.publish }}
        run: |
          VERSION="$(version-next "$(get-version)")"
          set-version "$VERSION"
          git commit -am "prepare for next version: $VERSION"
          git push && git push --tags
